version: 2.1

orbs:
#   chkk-orb: chkk/k8s@dev:beta
chkk-orb: muneeb131/butterflyorb@1.0.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
        - checkout
        - chkk-orb/scan:
              kubernetes-manifest: "kubernetes-sample-manifest.yaml"
              chkk-access-token: $CHKK_ACCESS_TOKEN
              continue-on-error: true
              run-checks: "CHKK-K8S-27,CHKK-K8S-28"
              show-diff: true
