version: 2.1

orbs:
    chkk-orb: chkk/k8s@dev:beta

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
        - checkout
        - chkk-orb/scan_directory:
              k8s-manifests-directory: "samples/"
              chkk-access-token: $CHKK_ACCESS_TOKEN
              continue-on-error: true
              show-diff: false
        - chkk-orb/scan_file:
              k8s-manifest: "kubernetes-sample-manifest.yaml"
              chkk-access-token: $CHKK_ACCESS_TOKEN
              continue-on-error: true
              show-diff: false
        - chkk-orb/scan_chart:
              helm-chart: "coredns/coredns"
              chkk-access-token: $CHKK_ACCESS_TOKEN
              continue-on-error: true
              show-diff: true
              args: "--set image.tag=1.8.3"
