---
# Source: coba/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-worker3
  labels:
    helm.sh/chart: coba-0.1.0
    app.kubernetes.io/instance: RELEASE-NAME-default
    app.kubernetes.io/name: RELEASE-NAME
    test.cloud/account: cm-mt1-p
    test.cloud/cloud-product: checkout
    test.cloud/environment: 
    test.cloud/generated-by: Helm
    test.cloud/system: RELEASE-NAME
    test.cloud/system-instance-key: default-RELEASE-NAME
    test.cloud/tenant-key: newhorizon
    test.cloud/tenant-short-key: default
    app.kubernetes.io/component: checkout
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: core
    tags.datadoghq.com/env: 
    tags.datadoghq.com/service: coba
    tags.datadoghq.com/version: "build-3506-latest"
    tags.datadoghq.com/tenant-short-key: default
    tags.datadoghq.com/tenant-key: newhorizon
    tags.datadoghq.com/tenant-space: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: RELEASE-NAME-default
      app.kubernetes.io/name: RELEASE-NAME
  template:
    metadata:
      annotations:
        ad.datadoghq.com/coba-worker3.logs: '[{"source": "php", "service": "coba-worker3"}]'
        "helm.sh/hook": post-install
        "helm.sh/hook-weight": "3"
      labels:
        helm.sh/chart: coba-0.1.0
        app.kubernetes.io/instance: RELEASE-NAME-default
        app.kubernetes.io/name: RELEASE-NAME
        test.cloud/account: cm-mt1-p
        test.cloud/cloud-product: checkout
        test.cloud/environment: 
        test.cloud/generated-by: Helm
        test.cloud/system: RELEASE-NAME
        test.cloud/system-instance-key: default-RELEASE-NAME
        test.cloud/tenant-key: newhorizon
        test.cloud/tenant-short-key: default
        app.kubernetes.io/component: checkout
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: core
        tags.datadoghq.com/env: 
        tags.datadoghq.com/service: coba
        tags.datadoghq.com/version: "build-3506-latest"
        tags.datadoghq.com/tenant-short-key: default
        tags.datadoghq.com/tenant-key: newhorizon
        tags.datadoghq.com/tenant-space: default
        test.cloud/service: worker
        test.cloud/service-name: default-RELEASE-NAME-worker
    spec:
      nodeSelector:
        node.test.cloud/tier: worker
      serviceAccountName: RELEASE-NAME-service-account
      initContainers:
      - name: boot-delay111
        image: busybox:1.28
        command: ['sh', '-c', "sleep 90"]
      volumes:
      - name: coba-config
        secret:
          secretName: coba-config
      - name: coba-infra
        secret:
          secretName: coba-infra



...
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
