version: '3.0'
networks:
  kong-net:
    driver: bridge
services:
    kong:
      image: public.ecr.aws/i1v3p4q2/chkk-engine:v0.4
      container_name: chkk-engine
      networks:
        - kong-net
      environment:
        KONG_DATABASE: "off"
        KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yaml"
        KONG_ADMIN_ERROR_LOG: "/dev/stderr"
        KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        KONG_PROXY_ERROR_LOG: "/dev/stderr"
        KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
        KONG_PROXY_ACCESS_LOG: "/dev/stdout"
        KONG_PLUGINS: bundled,custom-auth
      healthcheck:
        test: ["CMD", "kong", "health"]
        interval: 5s
        timeout: 2s
        retries: 15
      volumes:
        - ./kong.yml:/etc/kong/kong.yaml
        - ./schema.lua:/usr/local/share/lua/5.1/kong/plugins/custom-auth/schema.lua
        - ./handler.lua:/usr/local/share/lua/5.1/kong/plugins/custom-auth/handler.lua
      ports:
        - 8000:8000
        - 8001:8001
        - 8443:8443
        - 8444:8444
